let states=[],stateData=null,stateCode='',districtIndex=-1;const $=s=>document.querySelector(s),esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])),norm=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const F={u:0,n:1,d:2,sd:3,cl:4,v:5,p:6,cat:7,type:8,m:9,est:10,loc:11,from:12,to:13,rooms:14,other:15,teachers:16,students:17,pre:18,lon:19,lat:20};
const fmt=v=>v==null?'—':Number(v).toLocaleString('en-IN'), ratio=(a,b)=>a&&b?(a/b).toFixed(1)+':1':'—', dict=(k,i)=>i==null||i<0?'—':(stateData?.[k]?.[i]??'—');
async function init(){const [ss,meta]=await Promise.all([fetch('data/states.json').then(r=>r.json()),fetch('data/meta.json').then(r=>r.json())]);states=ss;$('#state').innerHTML='<option value="">Choose state / UT</option>'+ss.map(x=>`<option value="${x.code}">${esc(x.name)} · ${x.count.toLocaleString('en-IN')}</option>`).join('');$('#hint').textContent=`${meta.schools.toLocaleString('en-IN')} operational schools · dataset retrieved 12 Jan 2022 · direct UDISE lookup supported`;}
async function loadState(code){if(stateCode===code&&stateData)return stateData;stateCode=code;stateData=null;$('#count').textContent='Loading state data…';stateData=await (code==='09'
? Promise.all(['09-1','09-2','09-3'].map(p=>fetch(`data/s/${p}.json`).then(r=>{if(!r.ok)throw new Error('state data');return r.json()}))).then(parts=>{
    if(Array.isArray(parts[0])) return parts.flat();
    const listKey=Object.keys(parts[0]).find(k=>Array.isArray(parts[0][k]));
    if(!listKey) return parts[0];
    return {...parts[0],[listKey]:parts.flatMap(x=>x[listKey]||[])};
  })
: fetch(`data/s/${code}.json`).then(r=>{if(!r.ok)throw new Error('state data');return r.json()}));return stateData}
$('#state').onchange=async e=>{const st=states.find(x=>x.code===e.target.value),d=$('#district');districtIndex=-1;render([]);if(!st){d.disabled=true;d.innerHTML='<option value="">Choose district</option>';stateData=null;stateCode='';return}d.disabled=false;d.innerHTML='<option value="">Choose district</option>'+st.districts.map((x,i)=>`<option value="${i}">${esc(x.name)} · ${x.count.toLocaleString('en-IN')}</option>`).join('');await loadState(st.code);$('#count').textContent='Choose a district or search within this state.'};
$('#district').onchange=e=>{districtIndex=e.target.value===''?-1:Number(e.target.value);search()};
$('#q').oninput=debounce(async()=>{const q=$('#q').value.trim();if(/^\d{11}$/.test(q))await direct(q);else search()},100);$('#clear').onclick=()=>{$('#q').value='';search()};$('#close').onclick=()=>$('#dlg').close();function debounce(f,m){let t;return()=>{clearTimeout(t);t=setTimeout(f,m)}}
async function direct(u){const sc=u.slice(0,2),st=states.find(x=>x.code===sc);if(!st){render([]);return}$('#state').value=sc;const d=$('#district');d.disabled=false;d.innerHTML='<option value="">Choose district</option>'+st.districts.map((x,i)=>`<option value="${i}">${esc(x.name)} · ${x.count.toLocaleString('en-IN')}</option>`).join('');await loadState(sc);const hit=stateData.r.find(r=>r[F.u]===u);if(hit){districtIndex=hit[F.d];d.value=String(districtIndex);render([hit]);openSchool(hit)}else render([])}
function search(){if(!stateData){if($('#q').value.trim())$('#count').textContent='Choose a state, or enter an 11-digit UDISE code.';return}const q=norm($('#q').value),tokens=q.split(' ').filter(Boolean);let rows=stateData.r;if(districtIndex>=0)rows=rows.filter(r=>r[F.d]===districtIndex);if(q.length>=2)rows=rows.filter(r=>{const hay=norm([r[F.n],dict('sd',r[F.sd]),dict('v',r[F.v]),dict('p',r[F.p]),r[F.u]].join(' '));return tokens.every(t=>hay.includes(t))});render(rows.slice(0,120),rows.length)}
function render(rows,total=rows.length){const st=states.find(x=>x.code===stateCode);$('#grid').innerHTML=rows.map((r,i)=>`<article class="card" data-i="${i}"><div class="code">UDISE ${esc(r[F.u])}</div><h2>${esc(r[F.n])}</h2><div class="place">${esc(dict('d',r[F.d]))}${dict('sd',r[F.sd])!=='—'?` · ${esc(dict('sd',r[F.sd]))}`:''}<br>${esc(dict('v',r[F.v])!=='—'?dict('v',r[F.v]):dict('p',r[F.p]))}</div><div class="tags"><span class="tag">${esc(dict('m',r[F.m]))}</span><span class="tag">${esc(dict('cat',r[F.cat]))}</span></div></article>`).join('');$('#count').textContent=total?`${Math.min(total,120).toLocaleString('en-IN')} shown${total>120?` of ${total.toLocaleString('en-IN')}`:''}`:'';$('#empty').classList.toggle('hidden',rows.length>0||!$('#q').value.trim());document.querySelectorAll('.card').forEach((el,i)=>el.onclick=()=>openSchool(rows[i]))}
function openSchool(r){const st=states.find(x=>x.code===stateCode),students=r[F.students],teachers=r[F.teachers];$('#detail').innerHTML=`<div class="detail"><div class="code">UDISE ${esc(r[F.u])}</div><h2>${esc(r[F.n])}</h2><div class="sub">${esc(dict('v',r[F.v]))}, ${esc(dict('sd',r[F.sd]))}, ${esc(dict('d',r[F.d]))}, ${esc(st?.name)} ${esc(dict('p',r[F.p])==='—'?'':dict('p',r[F.p]))}</div><div class="sect">School snapshot</div><div class="kpis"><div class="kpi"><strong>${fmt(students)}</strong><span>Students</span></div><div class="kpi"><strong>${fmt(teachers)}</strong><span>Teachers</span></div><div class="kpi"><strong>${fmt(r[F.rooms])}</strong><span>Classrooms</span></div><div class="kpi light"><strong>${ratio(students,teachers)}</strong><span>Student : teacher</span></div><div class="kpi light"><strong>${esc((r[F.from]??'—')+'–'+(r[F.to]??'—'))}</strong><span>Classes</span></div><div class="kpi light"><strong>${fmt(r[F.est])}</strong><span>Established</span></div></div><div class="sect">School details</div><div class="info">${[['Management',dict('m',r[F.m])],['Category',dict('cat',r[F.cat])],['School type',dict('type',r[F.type])],['Location',dict('loc',r[F.loc])],['District',dict('d',r[F.d])],['Sub-district',dict('sd',r[F.sd])],['Cluster',dict('cl',r[F.cl])],['Village',dict('v',r[F.v])],['PIN code',dict('p',r[F.p])],['Pre-primary students',r[F.pre]],['Other rooms',r[F.other]],['Coordinates',r[F.lat]&&r[F.lon]?r[F.lat]+', '+r[F.lon]:null]].map(([k,v])=>`<div class="row"><small>${k}</small><strong>${esc(v)}</strong></div>`).join('')}</div><div class="actions"><button class="primary" id="shareStory">Share Story</button><button class="secondary" id="downloadStory">Download 1080×1920</button></div><div class="note"><strong>Data note:</strong> Ministry of Education UDISE data distributed via India Data Portal. The supplied dataset was retrieved on 12 January 2022; this is not a live 2026 KYS record.</div></div>`;$('#dlg').showModal();$('#shareStory').onclick=()=>story(r,true);$('#downloadStory').onclick=()=>story(r,false)}
function rr(c,x,y,w,h,r){c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath()}function wrap(c,t,x,y,w,lh,max){let ws=String(t).split(/\s+/),line='',ls=[];for(const z of ws){let q=line?line+' '+z:z;if(c.measureText(q).width>w&&line){ls.push(line);line=z;if(ls.length>=max)break}else line=q}if(ls.length<max&&line)ls.push(line);ls.forEach((z,i)=>c.fillText(z,x,y+i*lh));return y+ls.length*lh}
async function story(r,share){const st=states.find(x=>x.code===stateCode),W=1080,H=1920,p=82,cv=document.createElement('canvas'),c=cv.getContext('2d');cv.width=W;cv.height=H;c.fillStyle='#f4f5f7';c.fillRect(0,0,W,H);c.fillStyle='#ff4d00';c.font='900 26px system-ui';c.fillText('SCHOOL RECORDS INDIA',p,100);c.fillStyle='#111315';c.font='950 58px system-ui';let y=190;y=wrap(c,r[F.n],p,y,W-p*2,66,4)+18;c.fillStyle='#69717a';c.font='700 24px system-ui';c.fillText(`${dict('d',r[F.d])}, ${st?.name??''}`,p,y);y+=38;c.font='700 20px ui-monospace,monospace';c.fillText(`UDISE ${r[F.u]}`,p,y);y+=80;c.fillStyle='#ff4d00';c.font='900 21px system-ui';c.fillText('SCHOOL SNAPSHOT',p,y);y+=36;const its=[['STUDENTS',fmt(r[F.students])],['TEACHERS',fmt(r[F.teachers])],['CLASSROOMS',fmt(r[F.rooms])],['STUDENT : TEACHER',ratio(r[F.students],r[F.teachers])],['CLASSES',`${r[F.from]??'—'}–${r[F.to]??'—'}`],['ESTABLISHED',fmt(r[F.est])]];its.forEach((it,i)=>{let col=i%2,row=Math.floor(i/2),x=p+col*455,yy=y+row*150;c.fillStyle=i<3?'#111315':'#fff';rr(c,x,yy,420,125,23);c.fill();c.fillStyle=i<3?'#b9bec4':'#69717a';c.font='800 17px system-ui';c.fillText(it[0],x+24,yy+34);c.fillStyle=i<3?'#fff':'#111315';c.font='950 37px system-ui';c.fillText(String(it[1]),x+24,yy+83)});y+=495;c.fillStyle='#ff4d00';c.font='900 21px system-ui';c.fillText('DETAILS',p,y);y+=45;[['MANAGEMENT',dict('m',r[F.m])],['CATEGORY',dict('cat',r[F.cat])],['TYPE',dict('type',r[F.type])],['LOCATION',dict('loc',r[F.loc])],['SUB-DISTRICT',dict('sd',r[F.sd])],['PIN',dict('p',r[F.p])]].forEach(([k,v],i)=>{c.fillStyle='#69717a';c.font='800 16px system-ui';c.fillText(k,p,y+i*78);c.fillStyle='#111315';c.font='800 22px system-ui';wrap(c,v??'—',p+225,y+i*78,W-p*2-225,26,2)});c.fillStyle='#111315';rr(c,p,1515,W-p*2,205,28);c.fill();c.fillStyle='#fff';c.font='900 25px system-ui';c.fillText('PUBLIC UDISE SCHOOL DATA',p+36,1570);c.fillStyle='#b9bec4';c.font='650 19px system-ui';c.fillText('Ministry of Education / UDISE via India Data Portal',p+36,1612);c.fillText('Dataset retrieval date: 12 January 2022',p+36,1650);c.fillStyle='#69717a';c.font='650 17px system-ui';c.fillText('Independent interface · Not an official Government of India website',p,H-75);const blob=await new Promise(z=>cv.toBlob(z,'image/png')),file=new File([blob],`school-${r[F.u]}-story.png`,{type:'image/png'});if(share&&navigator.canShare&&navigator.canShare({files:[file]})){try{await navigator.share({files:[file],title:r[F.n]});return}catch(e){}}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}init();